# Generated by Django 3.1.3 on 2021-01-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_token', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmodel',
            name='assigned_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
